# Generated by Django 4.2.13 on 2024-06-01 15:58

from django.db import migrations
import useraccount.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_color',
            field=useraccount.customfields.RGBcolorField(max_length=6, null=True),
        ),
    ]
